# Generated by Django 4.2.3 on 2023-07-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_trainer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='slug',
            field=models.SlugField(),
        ),
    ]
