# Generated by Django 4.2.3 on 2023-08-06 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
        ('trainer', '0009_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True, help_text='Флаг публикующий комментарий на сайте', verbose_name='Вкл/Выкл'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='trainer.trainer', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=False, help_text='Флаг публикующий событие на сайте', verbose_name='Вкл/Выкл'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='О событии'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(verbose_name='Дата/время окончания'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(verbose_name='Дата/время начала'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_places',
            field=models.PositiveSmallIntegerField(verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='event',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trainer.trainer', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='active',
            field=models.BooleanField(default=True, help_text='Флаг публикующий тренера на сайте', verbose_name='Вкл/Выкл'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, None], upload_to='trainers/%Y/%m/%d/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='description',
            field=models.TextField(help_text='Укажите краткую биографию тренера', verbose_name='О тренере'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(help_text='Имя и фамилия тренера', max_length=50, verbose_name='Имя тренера'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='slug',
            field=models.SlugField(help_text='Уникальный постфикс тренера в урл-е', unique=True, verbose_name='Слаг'),
        ),
    ]
