# Generated by Django 4.2.3 on 2023-08-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Тема сообщения'),
        ),
    ]
